### ISSUE TITLE
Create html and js file

### ISSUE THREAD

**Issue by heyitscarloc** [heyitscarloc/super-todo-uper#2]
Create a blank html file and js file in the repository

**Comment by paintvvitch** [comment]
Hey Carlo, Can you please elaborate on what files to create here?

**Comment by paintvvitch** [comment]
@heyitscarloc please respond to my comment.

**Comment by heyitscarloc** [comment]
@paintvvitch hey i just updated the description. Let me know if that doesn't make sense.
